import { StyleSheet } from "react-native";
import { theme } from "../theme";
import { IS_TABLET, rs } from "../utils/responsive";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    flexGrow: 1,
    paddingVertical: 20,
    backgroundColor: theme.colors.background,
  },
  contentSection: {
    height: "100%",
    width: "100%",
    flexDirection: "column",
    backgroundColor: theme.colors.background,
  },
  loginSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.background,
  },
  loginButton: {
    flex: 1,
    height: "100%",
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  memberHeader: {
    minHeight: rs(80, 1.2),
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    backgroundColor: theme.colors.surface,
  },
  memberSection: {
    width: "100%",
    backgroundColor: "transparent",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginTop: 30,
    paddingTop: 50,
  },
  memberImage: {
    width: rs(100),
    height: rs(100),
    borderRadius: rs(100),
    borderWidth: 2,
    borderColor: theme.colors.gold,
  },
  membersOrders: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.gold + "40",
    borderLeftWidth: 0,
    borderRightWidth: 0,
    width: "100%",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  ordersShowMoreIcon: {
    position: "absolute",
    right: 0,
    top: -20,
    borderWidth: 1,
    borderColor: theme.colors.gold + "40",
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    height: 55,
    width: 55,
  },
  orderDetails: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  memberDetails: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    padding: 30,
  },
  memberDetailsTitle: {
    fontSize: 36,
    color: theme.colors.text,
    fontFamily: "Fraunces-Regular",
  },
  memberDetailsSubTitle: {
    fontSize: 20,
    color: theme.colors.textSecondary,
    marginTop: 10,
  },
  memberActionButton: {
    flex: 1,
    borderRadius: 8,
    fontFamily: "Fraunces-Regular",
  },
  accountInfo: {
    width: "100%",
    marginTop: 20,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  accountInfoTitle: {
    fontSize: 34,
    color: theme.colors.gold,
    marginTop: 20,
  },
  accountInfoSubtitle: {
    fontSize: 16,
    color: theme.colors.text,
    marginVertical: 20,
  },
  accountInfoText: {
    fontSize: 16,
    color: theme.colors.text,
  },
  accountInfoSmallText: {
    fontSize: 16,
    color: theme.colors.textSecondary,
  },
  accountInputContainer: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 10,
    marginVertical: 20,
  },
  accountInput: {
    width: "100%",
    minHeight: rs(40, 1.3),
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.gold + "60",
    borderRadius: 8,
    padding: rs(10, 1.3),
    fontFamily: "Fraunces-Regular",
    fontSize: rs(16, 1.1),
    color: theme.colors.text,
  },
});
